
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toifcjejcshrjfbgkdtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaWZjamVqY3NocmpmYmdrZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjIzODgsImV4cCI6MjA2Mjg5ODM4OH0.C6KwK-BUf8B5hYvjxjmC4AIU01lyHWAiBMLp69KrVdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get avatar URL based on avatar_id or custom URL
export const getAvatarSrc = (avatarUrl: string | null) => {
  if (!avatarUrl) return "https://i.pravatar.cc/150?img=5";
  
  // Check if it's a predefined avatar (avatarN) or a custom URL
  if (avatarUrl.startsWith('avatar')) {
    const { avatars } = require('@/components/AvatarSelector');
    const avatar = avatars.find((a: any) => a.id === avatarUrl);
    return avatar?.src || "https://i.pravatar.cc/150?img=5";
  }
  
  // It's a custom URL
  return avatarUrl;
};
