// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toifcjejcshrjfbgkdtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaWZjamVqY3NocmpmYmdrZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjIzODgsImV4cCI6MjA2Mjg5ODM4OH0.C6KwK-BUf8B5hYvjxjmC4AIU01lyHWAiBMLp69KrVdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get the avatar source URL
export const getAvatarSrc = (avatarUrl: string | null): string => {
  if (!avatarUrl) return "https://i.pravatar.cc/150?img=5";
  
  // If it's already a URL, return it
  if (avatarUrl.startsWith('http')) {
    return avatarUrl;
  }
  
  // Otherwise, get the URL from Supabase storage
  const { data } = supabase.storage
    .from('profiles')
    .getPublicUrl(avatarUrl);
    
  return data?.publicUrl || "https://i.pravatar.cc/150?img=5";
};
